import { BadRequestException, Inject, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Student } from './entities/student.entity';
import { Repository, DataSource } from 'typeorm';
import { CreateStudentDto } from './dtos/create-student.dto';
import { UsersService } from '../users/users.service';
import { User } from '../users/entities/user.entity';
import { Department, EnrollmentStatus, Gender, Level, Role } from '../../utils/enum';
import { UpdateStudentDto } from './dtos/update-student.dto';
import { Enrollment } from '../enrollments/entities/enrollment.entity';

@Injectable()
export class StudentsService {
  constructor(
    private readonly dataSource: DataSource,
    @InjectRepository(Student)
    private readonly studentRepository: Repository<Student>,
    @InjectRepository(Enrollment)
    private readonly enrollmentRepository: Repository<Enrollment>,
    @InjectRepository(User)
    private readonly userRepository: Repository<User>,
    private readonly usersService: UsersService,
  ) { }

  /**
   * Create a new student
   * @param dto {user: CreateUserDto, student: CreateStudentDto}
   * @returns {message: string, data: {user: User, student: Student}}
   */
  public async createStudent(dto: CreateStudentDto) {

    const { user, ...studentData } = dto;

    // We didn't use usersService.findByNationalId(user.national_id)
    // Because it will throw an error if the user is not found
    // We want to check if the user exists and if it does, we want to update it
    // If it doesn't exist, we want to create it
    const existingUser = await this.userRepository.findOne({
      where: { national_id: user.national_id },
    });
    if (existingUser) {
      throw new BadRequestException('User with this national_id already exists');
    }

    const existingStudent = await this.studentRepository.findOne({
      where: { student_code: studentData.student_code },
    });
    if (existingStudent) {
      throw new BadRequestException('Student code already in use');
    }

    return await this.dataSource.transaction(async (manager) => {
      const newUser = manager.create(User, {
        full_name: user.full_name,
        national_id: user.national_id,
        email: user.email,
        phone: user.phone,
        address: user.address,
        role: Role.STUDENT,
        password_hash: null,
        is_password_set: false,
        date_of_birth: new Date(user.date_of_birth),
        gender: user.gender,
      });

      const savedUser = await manager.save(newUser);

      const newStudent = manager.create(Student, {
        id: savedUser.id,
        user: savedUser,

        ...studentData,

        enrollment_date: studentData.enrollment_date ? new Date(studentData.enrollment_date) : new Date(),
      });

      const savedStudent = await manager.save(newStudent);

      return {
        message: 'Student created successfully',
        data: {
          user: savedUser,
          student: savedStudent,
        },
      };
    });
  }

  /**
   * Get all students
   * @returns {message: string, data: {students: Student[]}}
   */
  public async getAllStudents(
    level?: Level,
    department?: Department,
    gender?: Gender
  ) {

    let students = await this.studentRepository.find({
      relations: ['user'],
      where: {
        level,
        department,
      },
    });

    if (gender) {
      students = students.filter((student) => student.user.gender === gender);
    }

    return {
      message: 'Students fetched successfully',
      data: {
        students,
      },
    };
  }

  /**
   * Get student by code, Student code is unique and always generated by the system, 
   * and assigned to the student when created
   * @param student_code
   * @returns
   */
  public async getStudentByCode(student_code: string) {
    const student = await this.studentRepository.findOne({
      where: { student_code },
      relations: ['user', 'enrollments', 'enrollments.course'],
    });
    if (!student) {
      throw new BadRequestException('Student not found');
    }
    return student;
  }

  /**
   * Get student by id
   * @param id
   * @returns {
   * message: string,
   * data: {
   * student: {
   * id: string,
   * student_code: string,
   * enrollment_date: Date,
   * level: Level,
   * semester: number,
   * department: Department,
   * user_id: string,
   * user: User,
   * enrollments: Enrollment[]
   * },
   * },
   * }
   */
  public async getStudentById(id: string): Promise<Student> {
    const student = await this.studentRepository.findOne({
      where: { id },
      relations: ['user', 'enrollments', 'enrollments.course'],
    });

    if (!student) {
      throw new NotFoundException('Student not found');
    }

    return student;
  }

  /**
   * Get student GPA and CGPA for student dashboard
   * @param student_id
   * @returns
   */
  public async getStudentGPAandCGPA(student_id: string) {
    const student = await this.studentRepository.findOne({
      where: { id: student_id },
    });
    if (!student) {
      throw new NotFoundException('Student not found');
    }
    return {
      cgpa: student.cgpa,
      gpa: student.gpa,
    };
  }


  /**
   * Get student dashboard
   * @param student_id
   * @returns {
   * message: string,
   * data: {
   * student: {
   * name: string,
   * code: string,
   * level: Level,
   * semester: number,
   * department: Department,
   * },
   * coursesStats: {
   * totalCourses: number,
   * progressCourses: Course[],
   * completedCourses: Course[],
   * },
   * },
   * }
   */
  public async studentDashboard(student_id: string) {
    const student = await this.getStudentById(student_id);

    if (student.display_content === false) {
      return {
        message: 'Student dashboard is not available',
        data: null,
      };
    }

    const progressCourses = student.enrollments.
      filter((enrollment) => enrollment.status === EnrollmentStatus.IN_PROGRESS)
      .map((enrollment) => enrollment.course);
    const academicEstimation = this.estimate(student.gpa);
    return {
      message: 'Student dashboard fetched successfully',
      data: {
        student: {
          name: student.user.full_name,
          code: student.student_code,
          level: student.level,
          semester: student.semester,
          department: student.department,
          cgpa: student.cgpa,
          gpa: student.gpa,
          academicEstimation,
        },
        coursesStats: {
          totalCourses: student.enrollments.length,
          progressCourses,
        },
      },
    };
  }


  /**
   * Get student completed courses
   * @param student_id
   * @returns
   */
  public async getStudentCompletedCourses(student_id: string) {
    const student = await this.getStudentById(student_id);
    const completedCourses = student.enrollments.
      filter((enrollment) => enrollment.status === EnrollmentStatus.PASSED)
      .map((enrollment) => enrollment.course);
    return {
      message: 'Student completed courses fetched successfully',
      data: {
        completedCourses,
      },
    };
  }


  /**
   * Get student courses by status
   * @param student_id
   * @param course_status
   * @returns
   */
  public async getStudentCourses(student_id: string, course_status?: EnrollmentStatus) {
    const student = await this.getStudentById(student_id);

    const enrollments = await this.enrollmentRepository.find({
      where: {
        student: student,
        status: course_status,
      },
      relations: ['course'],
    });

    return {
      message: 'Student courses fetched successfully',
      data: {
        enrollments,
      },
    };
  }

  /**
   * Update student
   * @param id
   * @param dto
   * @returns
   */
  public async updateStudent(id: string, dto: UpdateStudentDto) {
    const { user, ...studentFields } = dto;

    await this.studentRepository.manager.transaction(async (manager) => {
      const studentUpdates = Object.fromEntries(
        Object.entries(studentFields).filter(([_, v]) => v !== undefined)
      );

      if (Object.keys(studentUpdates).length > 0) {
        await manager.update(Student, id, studentUpdates);
      }

      if (user) {
        const student = await manager.findOne(Student, {
          where: { id },
          select: { user: { id: true } },
          relations: ['user'],
        });

        if (!student) throw new NotFoundException(`Student ${id} not found`);

        const userUpdates = Object.fromEntries(
          Object.entries(user).filter(([_, v]) => v !== undefined)
        );

        if (Object.keys(userUpdates).length > 0) {
          await manager.update(User, student.user.id, userUpdates);
        }
      }
    });

    return this.getStudentById(id);
  }

  /**
   * Delete student
   * @param id
   * @returns
   */
  public async deleteStudent(id: string) {
    const student = await this.studentRepository.findOne({
      where: { id },
      relations: ['user'],
    });
    if (!student) {
      throw new NotFoundException('Student not found');
    }
    await this.studentRepository.delete(student.id);
    await this.userRepository.delete({ id: student.user.id });
    return {
      message: 'Student deleted successfully',
    };
  }

  // Get Number of Students
  public async getNumberOfStudents() {
    return this.studentRepository.count();
  }

  public async toggleContentAccess(id: string) {
    const student = await this.studentRepository.findOne({
      where: { id },
    });

    if (!student) {
      throw new NotFoundException('Student not found');
    }

    student.display_content = !student.display_content;

    await this.studentRepository.save(student);

    return {
      message: `Content access ${student.display_content ? 'enabled' : 'disabled'
        } successfully`,
      has_content_access: student.display_content,
    };
  }

  // Get Academic Estimation
  public estimate(gpa: number) {
    if (gpa >= 3.6) {
      return 'Excellent';
    }
    if (gpa >= 3.0) {
      return 'Very Good';
    }
    if (gpa >= 2.0) {
      return 'Good';
    }
    if (gpa >= 1.0) {
      return 'Pass';
    }
    return 'Fail';
  }
}
