import { BadRequestException, Inject, Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Student } from './entities/student.entity';
import { Repository, DataSource } from 'typeorm';
import { CreateStudentDto } from './dtos/create-student.dto';
import { UsersService } from 'src/users/users.service';
import { User } from 'src/users/entities/user.entity';
import { Department, EnrollmentStatus, Gender, Level, Role } from 'utils/enum';
import { UpdateStudentDto } from './dtos/update-student.dto';
import { Enrollment } from 'src/enrollments/entities/enrollment.entity';

@Injectable()
export class StudentsService {
  constructor(
    private readonly dataSource: DataSource,
    @InjectRepository(Student)
    private readonly studentRepository: Repository<Student>,
    @InjectRepository(Enrollment)
    private readonly enrollmentRepository: Repository<Enrollment>,
    private readonly usersService: UsersService,
  ) { }

  /**
   * Create a new student
   * @param dto {user: CreateUserDto, student: CreateStudentDto}
   * @returns {message: string, data: {user: User, student: Student}}
   */
  public async createStudent(dto: CreateStudentDto, admin_id: string) {
    await this.usersService.checkValidation(admin_id, Role.ADMIN);
    const { user, ...studentData } = dto;
    await this.usersService.findByNationalId(user.national_id);

    const existingStudent = await this.studentRepository.findOne({
      where: { student_code: studentData.student_code },
    });
    if (existingStudent) {
      throw new BadRequestException('Student code already in use');
    }

    return await this.dataSource.transaction(async (manager) => {
      const newUser = manager.create(User, {
        full_name: user.full_name,
        national_id: user.national_id,
        email: user.email,
        phone: user.phone,
        address: user.address,
        role: Role.STUDENT,
        password_hash: null,
        is_password_set: false,
        date_of_birth: new Date(user.date_of_birth),
        gender: user.gender,
      });

      const savedUser = await manager.save(newUser);

      const newStudent = manager.create(Student, {
        id: savedUser.id,
        user: savedUser,

        ...studentData,

        enrollment_date: new Date(studentData.enrollment_date),
      });

      const savedStudent = await manager.save(newStudent);

      return {
        message: 'Student created successfully',
        data: {
          user: savedUser,
          student: savedStudent,
        },
      };
    });
  }

  /**
   * Get all students
   * @returns {message: string, data: {students: Student[]}}
   */
  public async getAllStudents(
    level?: Level,
    department?: Department,
    gender?: Gender
  ) {

    let students = await this.studentRepository.find({
      relations: ['user'],
      where: {
        level,
        department,
      },
    });

    if (gender) {
      students = students.filter((student) => student.user.gender === gender);
    }

    return {
      message: 'Students fetched successfully',
      data: {
        students,
      },
    };
  }

  /**
   * Get student by code, Student code is unique and always generated by the system, 
   * and assigned to the student when created
   * @param student_code
   * @returns
   */
  public async getStudentByCode(student_code: string) {
    const student = await this.studentRepository.findOne({
      where: { student_code },
      relations: ['user', 'enrollments', 'enrollments.course'],
    });
    if (!student) {
      throw new BadRequestException('Student not found');
    }
    return student;
  }

  /**
   * Get student by id
   * @param id
   * @returns
   */
  public async getStudentById(id: string) {
    const student = await this.studentRepository.findOne({
      where: { id },
      relations: ['user', 'enrollments', 'enrollments.course'],
    });

    if (!student) {
      throw new NotFoundException('Student not found');
    }

    return student;
  }

  public async studentDashboard(student_id: string) {
    const student = await this.getStudentById(student_id);
    const progressCourses = student.enrollments.
      filter((enrollment) => enrollment.status === EnrollmentStatus.IN_PROGRESS)
      .map((enrollment) => enrollment.course);
    const completedCourses = student.enrollments.
      filter((enrollment) => enrollment.status === EnrollmentStatus.PASSED)
      .map((enrollment) => enrollment.course);
    return {
      message: 'Student dashboard fetched successfully',
      data: {
        student:{
          name:student.user.full_name,
          code:student.student_code,
          level:student.level,
          semester:student.semester,
          department:student.department,
        },
        coursesStats: {
          totalCourses: student.enrollments.length,
          progressCourses,
          completedCourses,
        },
      },
    };
  }


  /**
   * Get student completed courses
   * @param student_id
   * @returns
   */
  public async getStudentCompletedCourses(student_id: string) {
    const student = await this.getStudentById(student_id);
    return student.enrollments.filter((enrollment) => enrollment.status === EnrollmentStatus.PASSED).map((enrollment) => enrollment.course);
  }


  /**
   * Get student courses by status
   * @param student_id
   * @param course_status
   * @returns
   */
  public async getStudentCourses(student_id: string, course_status?: EnrollmentStatus) {
    const student = await this.getStudentById(student_id);

    const enrollments = await this.enrollmentRepository.find({
      where: {
        student: student,
        status: course_status,
      },
      relations: ['course'],
    });

    return {
      message: 'Student courses fetched successfully',
      data: {
        enrollments,
      },
    };
  }

  /**
   * Update student
   * @param id
   * @param dto
   * @returns
   */
  public async updateStudent(id: string, dto: UpdateStudentDto) {
    const student = await this.getStudentById(id);
    if (!student) {
      throw new NotFoundException('Student not found');
    }
    return await this.studentRepository.update(id, dto);
  }
}
