import { BadRequestException, Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Student } from './entities/student.entity';
import { Repository, DataSource } from 'typeorm';
import { CreateStudentDto } from './dtos/create-student.dto';
import { UsersService } from 'src/users/users.service';
import { User } from 'src/users/entities/user.entity';
import { Role } from 'utils/enum';

@Injectable()
export class StudentsService {
  constructor(
    private readonly dataSource: DataSource,
    @InjectRepository(Student)
    private readonly studentRepository: Repository<Student>,
    @InjectRepository(User)
    private readonly userRepository: Repository<User>,
    private readonly usersService: UsersService,
  ) {}

  /**
   * Create a new student
   * @param dto {user: CreateUserDto, student: CreateStudentDto}
   * @returns {message: string, data: {user: User, student: Student}}
   */
  public async createStudent(dto: CreateStudentDto, admin_id: string) {
    await this.usersService.checkValidation(admin_id, Role.ADMIN);
    
    const { user, ...studentData } = dto;

    const existingUser = await this.userRepository.findOne({
      where: { national_id: user.national_id },
    });
    if (existingUser) {
      throw new BadRequestException('National ID already in use');
    }

    const existingStudent = await this.studentRepository.findOne({
      where: { student_code: studentData.student_code },
    });
    if (existingStudent) {
      throw new BadRequestException('Student code already in use');
    }

    return await this.dataSource.transaction(async (manager) => {
      const newUser = manager.create(User, {
        full_name: user.full_name,
        national_id: user.national_id,
        email: user.email,
        phone: user.phone,
        address: user.address,
        role: Role.STUDENT,
        password_hash: null,
        is_password_set: false,
        date_of_birth: new Date(user.date_of_birth),
        gender: user.gender,
      });

      const savedUser = await manager.save(newUser);

      const newStudent = manager.create(Student, {
        id: savedUser.id,
        user: savedUser,

        ...studentData,

        enrollment_date: new Date(studentData.enrollment_date),
      });

      const savedStudent = await manager.save(newStudent);

      return {
        message: 'Student created successfully',
        data: {
          user: savedUser,
          student: savedStudent,
        },
      };
    });
  }

  /**
   * Get student by code, Student code is unique and always generated by the system, and assigned to the student when created
   * @param student_code
   * @returns
   */
  public async getStudentByCode(student_code: string) {
    const student = await this.studentRepository.findOne({
      where: { student_code },
      relations: ['user'],
    });
    if (!student) {
      throw new BadRequestException('Student not found');
    }
    return student;
  }
}
